*   [33m9e99469[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mmain[m[33m, [m[1;31morigin/main[m[33m, [m[1;31morigin/HEAD[m[33m)[m Add 'LLMOPS/Phising/' from commit '0bf4f0b0122821992918c18e14026d01690f403e'
[31m|[m[32m\[m  
[31m|[m * [33m0bf4f0b[m code updated
[31m|[m * [33m43b006c[m code updated
[31m|[m * [33md66192b[m code updated
[31m|[m * [33m3e0b460[m updated
[31m|[m * [33m51f9a3e[m code updated
[31m|[m * [33m3a6650f[m code updated
[31m|[m * [33m5501d9a[m code updated
[31m|[m * [33mbc15b7f[m file name has changed
[31m|[m * [33m2bb4047[m code is updated
[31m|[m * [33me9a03a2[m requirement upadted with the latest require module for url parsing
[31m|[m * [33m469f977[m code is up to date
[31m|[m * [33m2a5999d[m code is updated with mlflow
[31m|[m * [33ma9cb32e[m code update
[31m|[m * [33m1df778b[m code updated
[31m|[m * [33m4df7032[m code updated
[31m|[m * [33m5c93c83[m code updated
[31m|[m * [33m5ea84e6[m code updated
[31m|[m * [33mf19f03a[m code updated
[31m|[m * [33m8570e7e[m config_loader updated
[31m|[m * [33m357dd96[m code updated in config.yaml
[31m|[m * [33mbdb5842[m pipeline.py initlize
[31m|[m * [33mfe7beef[m code foldar is updated
[31m|[m * [33m74dd55f[m eda file is updated
[31m|[m * [33md4fb337[m eda code updated
[31m|[m * [33m3990c1f[m 6th project setup is done and data provided in the notebook folder
*   [33m5ead8c9[m Add 'Devops/' from commit '76fb7daa0090c9dcfff2244c6595205c61ce0807'
[33m|[m[34m\[m  
[33m|[m * [33m76fb7da[m Create instruction.txt
[33m|[m * [33mf5d3315[m Create test_case_lambda.json
[33m|[m * [33m66221bb[m Initial Commit
[33m|[m * [33m2395201[m Create lambda_function.py
[33m|[m * [33mb40af19[m Initial commit
*   [33mf4aaa47[m Add 'Blogger/' from commit '43444aba770cd8a12859855e341bc58f871b8c4e'
[35m|[m[36m\[m  
[35m|[m * [33m43444ab[m Add files via upload
[35m|[m * [33mf85f715[m Delete app.py
[35m|[m * [33m9b8fdca[m Create sample.txt
[35m|[m * [33mc43ff3a[m Create requirements.txt
[35m|[m * [33m17dd575[m Create app.py
[35m|[m * [33m70c5830[m Create fetch_image.py
[35m|[m * [33m09ccd1d[m Initial commit
*   [33m13c5000[m Add 'PetCare/' from commit '53ae67c211248a020c053b3b3711e5989add45f0'
[1;31m|[m[1;32m\[m  
[1;31m|[m * [33m53ae67c[m Update llm.py
[1;31m|[m * [33mdc5228f[m Update langchain_aws.py
[1;31m|[m * [33mef4e872[m Update app.py
[1;31m|[m * [33m3cd374b[m Initial Commit
[1;31m|[m * [33m25feeb8[m Initial Commit
[1;31m|[m * [33m60cf55b[m Initial commit
*   [33mde54362[m Merge branch 'main' of https://github.com/amlanacharya/portfolio
[1;33m|[m[1;34m\[m  
[1;33m|[m * [33mebc6b94[m Sanitised
* [1;34m|[m   [33m55cebe4[m Add 'podcast/' from commit '0149fc18f6eafb2e94da8a6f5abaabd77a761d27'
[1;34m|[m[1;36m\[m [1;34m\[m  
[1;34m|[m [1;36m|[m[1;34m/[m  
[1;34m|[m[1;34m/[m[1;36m|[m   
[1;34m|[m * [33m0149fc1[m changed requirement.txt
[1;34m|[m * [33mf03e13e[m Update app.py
[1;34m|[m * [33me23b930[m Initial Commit
[1;34m|[m * [33medb1174[m Initial commit
*   [33ma115f31[m Add 'Llam2RAG/' from commit '3dba8d5061a80cb98425e51a1a3bc8ffdf5388a6'
[31m|[m[32m\[m  
[31m|[m * [33m3dba8d5[m Update README.md
[31m|[m * [33m5e40d98[m init commit
*   [33mc2f483d[m Add 'edtech/Chatbot_Tutorial/' from commit '7d8e009400d6a649caf3786a703331953fcb600e'
[33m|[m[34m\[m  
[33m|[m *   [33m7d8e009[m Merge branch 'main' of https://github.com/amlanacharya/Chatbot_Tutorial
[33m|[m [35m|[m[36m\[m  
[33m|[m [35m|[m * [33m56dd99d[m Update README.md
[33m|[m * [36m|[m [33m8e0ef4e[m fixes
[33m|[m [36m|[m[36m/[m  
[33m|[m * [33mb8ded07[m render fixes
[33m|[m * [33mc83d652[m TD updates
[33m|[m * [33m39f28ef[m Module14-fixes
[33m|[m * [33m21b564e[m Module 14
[33m|[m * [33m095b60f[m Module 13
[33m|[m * [33m92d18db[m module12
[33m|[m * [33m3db264f[m module9-11
[33m|[m * [33m77ceb36[m Update syllabus.md
[33m|[m * [33m577299f[m Update syllabus.md
[33m|[m * [33m6713b09[m Update syllabus.md
[33m|[m * [33m4c76c6f[m Update README.md
[33m|[m * [33m32b0910[m Update syllabus.md
[33m|[m * [33m2a40b54[m Add custom GroqLLM implementation for chat model, including API integration and conversation management. Update get_llm and get_conversation_chain functions to utilize the new model. Refactor message history extraction for improved handling.
[33m|[m * [33m01d6a2d[m Add model management and performance tracking features in module6 and module7. Implement endpoints for changing models, updating parameters, and comparing models. Enhance UI in module7 to display performance metrics and comparison results.
[33m|[m * [33m5be1289[m Implement chat interface in module7, including message display and user input handling.
[33m|[m * [33mac836cf[m Add root endpoint for API information, update message history structure, and introduce parameter ranges endpoint
[33m|[m * [33mddfbe89[m added todo
[33m|[m * [33m6cbb00d[m Delete .gradio directory
[33m|[m * [33m08bb8ea[m module 1-8
[33m|[m * [33m7f835a5[m api_test
[33m|[m * [33mf4f60a5[m Create groq_test.py
[33m|[m * [33m79aa936[m Create syllabus.md
[33m|[m * [33m49b88ce[m Update README.md
[33m|[m * [33mad843f1[m Initial commit
* [33mb2506a1[m Add prototype file for kycmask
*   [33mf6f7cf5[m Merge branch 'main' of https://github.com/amlanacharya/portfolio
[1;31m|[m[1;32m\[m  
[1;31m|[m * [33m6bbd921[m Delete Extra iamge
[1;31m|[m * [33md54d7d2[m Delete unwanted
[1;31m|[m * [33m214ecc0[m Edit
[1;31m|[m * [33m4d0db41[m Update README.md
* [1;32m|[m   [33mc4ae947[m Add 'kycmask/' from commit 'f5042f212594878e1a18327bffc221a9d66253db'
[1;32m|[m[1;34m\[m [1;32m\[m  
[1;32m|[m [1;34m|[m[1;32m/[m  
[1;32m|[m[1;32m/[m[1;34m|[m   
[1;32m|[m * [33mf5042f2[m UI updatex
[1;32m|[m * [33m7cc46d9[m reqt xt update
[1;32m|[m * [33med995c1[m initial commit
[1;32m|[m * [33m590d528[m Initial commit
* [33me555323[m Convert whatsapp-agent from submodule to tracked files
* [33m057b496[m Added WA Agent
* [33m6773232[m Added realtime-phone-agents project
* [33m3f581e7[m reset
* [33m7d62ced[m Added realtime-phone-agents project
* [33mb094e40[m further correction
* [33m37a5386[m Disclaimer edit and License declaration
* [33me695388[m Initial portfolio setup
* [33m30c618a[m Added paper-to-notebook project
* [33mef705c6[m Initial portfolio setup
