version: 2

models:
  - name: dim_date
    description: "Date dimension table for time-based analysis"
    columns:
      - name: date_key
        description: "Primary key in YYYYMMDD format"
        tests:
          - unique
          - not_null
      - name: calendar_date
        description: "Actual date"
        tests:
          - not_null
      - name: year
        description: "Calendar year"
      - name: month
        description: "Calendar month (1-12)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 12
      - name: day
        description: "Day of month (1-31)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 31
      - name: quarter
        description: "Calendar quarter (1-4)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 4
      - name: day_of_week
        description: "Day of week (0=Sunday, 6=Saturday)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 6
      - name: day_of_year
        description: "Day of year (1-366)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 366
      - name: is_weekend
        description: "Flag indicating if date is a weekend"
      - name: is_holiday
        description: "Flag indicating if date is an Indian holiday"
      - name: is_festival_season
        description: "Flag indicating if date is during festival season (Sep-Nov)"
      - name: fiscal_year
        description: "Fiscal year (April-March)"
      - name: fiscal_quarter
        description: "Fiscal quarter (1-4, starting in April)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 1
              max_value: 4
      - name: season
        description: "Season (Spring, Summer, Monsoon, Autumn, Winter)"
        tests:
          - accepted_values:
              values: ['Spring', 'Summer', 'Monsoon', 'Autumn', 'Winter']
      - name: month_name
        description: "Full name of the month"
        tests:
          - accepted_values:
              values: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
      - name: day_name
        description: "Full name of the day of the week"
        tests:
          - accepted_values:
              values: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

  - name: dim_customers
    description: "Customer dimension table for customer analysis"
    columns:
      - name: customer_id
        description: "Primary key - unique identifier for the customer"
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: "Unique identifier that represents a customer across the platform"
        tests:
          - not_null
      - name: customer_zip_code_prefix
        description: "First digits of customer zip code"
      - name: customer_city
        description: "Customer city name"
      - name: customer_state
        description: "Customer state"
      - name: region
        description: "Geographic region in Brazil (Southeast, South, etc.)"
        tests:
          - accepted_values:
              values: ['Southeast', 'South', 'Central-West', 'Northeast', 'North', 'Unknown']
      - name: valid_from
        description: "Timestamp when this dimension record became valid"
        tests:
          - not_null
      - name: valid_to
        description: "Timestamp when this dimension record became invalid (null if current)"
      - name: is_current
        description: "Flag indicating if this is the current record for the customer"
        tests:
          - not_null

  - name: dim_products
    description: "Product dimension table for product analysis"
    columns:
      - name: product_id
        description: "Primary key - unique identifier for the product"
        tests:
          - unique
          - not_null
      - name: product_category_name
        description: "Category name of the product"
      - name: product_name_length
        description: "Length of the product name"
      - name: product_description_length
        description: "Length of the product description"
      - name: product_photos_qty
        description: "Number of product photos"
      - name: product_weight_g
        description: "Weight of the product in grams"
      - name: product_length_cm
        description: "Length of the product in centimeters"
      - name: product_height_cm
        description: "Height of the product in centimeters"
      - name: product_width_cm
        description: "Width of the product in centimeters"
      - name: weight_category
        description: "Categorized weight (Light, Medium, Heavy, Very Heavy)"
        tests:
          - accepted_values:
              values: ['Light', 'Medium', 'Heavy', 'Very Heavy']
      - name: volume_cm3
        description: "Volume of the product in cubic centimeters"
      - name: size_category
        description: "Categorized size (Small, Medium, Large, Extra Large)"
        tests:
          - accepted_values:
              values: ['Small', 'Medium', 'Large', 'Extra Large']
      - name: valid_from
        description: "Timestamp when this dimension record became valid"
        tests:
          - not_null
      - name: valid_to
        description: "Timestamp when this dimension record became invalid (null if current)"
      - name: is_current
        description: "Flag indicating if this is the current record for the product"
        tests:
          - not_null

  - name: dim_sellers
    description: "Seller dimension table for seller analysis"
    columns:
      - name: seller_id
        description: "Primary key - unique identifier for the seller"
        tests:
          - unique
          - not_null
      - name: seller_zip_code_prefix
        description: "First digits of seller zip code"
      - name: seller_city
        description: "Seller city name"
      - name: seller_state
        description: "Seller state"
      - name: region
        description: "Geographic region in Brazil (Southeast, South, etc.)"
        tests:
          - accepted_values:
              values: ['Southeast', 'South', 'Central-West', 'Northeast', 'North', 'Unknown']
      - name: valid_from
        description: "Timestamp when this dimension record became valid"
        tests:
          - not_null
      - name: valid_to
        description: "Timestamp when this dimension record became invalid (null if current)"
      - name: is_current
        description: "Flag indicating if this is the current record for the seller"
        tests:
          - not_null
