version: 2

models:
  - name: int_orders_with_items
    description: "Orders enriched with item details and metrics"
    columns:
      - name: order_id
        description: "Unique identifier of the order"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Customer identifier"
        tests:
          - not_null
      - name: order_status
        description: "Current status of the order"
      - name: order_purchase_timestamp
        description: "Timestamp when the purchase was made"
      - name: order_approved_at
        description: "Timestamp when the payment was approved"
      - name: order_delivered_carrier_date
        description: "Timestamp when the order was handed to the logistics partner"
      - name: order_delivered_customer_date
        description: "Timestamp when the order was delivered to the customer"
      - name: order_estimated_delivery_date
        description: "Estimated delivery date provided to customer"
      - name: item_count
        description: "Number of items in the order"
      - name: order_items_value
        description: "Total value of items in the order"
      - name: order_freight_value
        description: "Total freight value for the order"
      - name: payment_value
        description: "Total payment value"
      - name: payment_types
        description: "Array of payment types used"
      - name: max_installments
        description: "Maximum number of installments used"
      - name: delivery_time_days
        description: "Actual delivery time in days"
      - name: estimated_delivery_time_days
        description: "Estimated delivery time in days"
      - name: delivery_delay_days
        description: "Delay in delivery (actual - estimated)"
      - name: is_delayed
        description: "Flag indicating if the order was delayed"
      - name: is_canceled
        description: "Flag indicating if the order was canceled"

  - name: int_customer_orders
    description: "Customer order history and metrics"
    columns:
      - name: customer_id
        description: "Unique identifier for a customer"
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: "Unique identifier that represents a customer across the platform"
      - name: customer_city
        description: "Customer city name"
      - name: customer_state
        description: "Customer state"
      - name: first_order_date
        description: "Date of the customer's first order"
      - name: last_order_date
        description: "Date of the customer's most recent order"
      - name: order_count
        description: "Total number of orders placed by the customer"
      - name: delivered_order_count
        description: "Number of orders successfully delivered to the customer"
      - name: canceled_order_count
        description: "Number of orders canceled by the customer"
      - name: total_items
        description: "Total number of items purchased by the customer"
      - name: total_order_value
        description: "Total value of all orders placed by the customer"
      - name: total_freight_value
        description: "Total freight value of all orders placed by the customer"
      - name: avg_order_value
        description: "Average order value for the customer"
      - name: avg_items_per_order
        description: "Average number of items per order"
      - name: days_since_last_order
        description: "Number of days since the customer's last order"
      - name: days_between_first_last_order
        description: "Number of days between the customer's first and last order"
      - name: avg_days_between_orders
        description: "Average number of days between orders"
      - name: customer_lifetime_value
        description: "Calculated lifetime value of the customer"

  - name: int_product_orders
    description: "Product order history and metrics"
    columns:
      - name: product_id
        description: "Unique identifier for a product"
        tests:
          - unique
          - not_null
      - name: product_category_name
        description: "Category name in original language"
      - name: product_category_name_english
        description: "Category name in English"
      - name: product_length_cm
        description: "Product length in centimeters"
      - name: product_height_cm
        description: "Product height in centimeters"
      - name: product_width_cm
        description: "Product width in centimeters"
      - name: product_weight_g
        description: "Product weight in grams"
      - name: order_count
        description: "Number of orders containing this product"
      - name: item_count
        description: "Total number of units sold"
      - name: total_revenue
        description: "Total revenue generated by this product"
      - name: total_freight_value
        description: "Total freight value for this product"
      - name: first_order_date
        description: "Date of the first order containing this product"
      - name: last_order_date
        description: "Date of the most recent order containing this product"
      - name: avg_price
        description: "Average price of the product"
      - name: customer_count
        description: "Number of unique customers who purchased this product"
      - name: product_volume_cm3
        description: "Volume of the product in cubic centimeters"
      - name: product_density
        description: "Density of the product (g/cm³)"

  - name: int_customer_behavior
    description: "Comprehensive customer behavior profiles combining order, clickstream, app usage, support, and review data"
    columns:
      - name: customer_id
        description: "Unique identifier for a customer"
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: "Unique identifier that represents a customer across the platform"
      - name: customer_city
        description: "Customer city name"
      - name: customer_state
        description: "Customer state"
      - name: first_order_date
        description: "Date of the customer's first order"
      - name: last_order_date
        description: "Date of the customer's most recent order"
      - name: order_count
        description: "Total number of orders placed by the customer"
      - name: delivered_order_count
        description: "Number of orders successfully delivered to the customer"
      - name: canceled_order_count
        description: "Number of orders canceled by the customer"
      - name: total_order_value
        description: "Total value of all orders placed by the customer"
      - name: avg_order_value
        description: "Average order value for the customer"
      - name: days_since_last_order
        description: "Number of days since the customer's last order"
      - name: customer_lifetime_value
        description: "Calculated lifetime value of the customer"
      - name: total_events
        description: "Total number of clickstream events"
      - name: total_sessions
        description: "Total number of web sessions"
      - name: active_days
        description: "Number of days with website activity"
      - name: page_view_count
        description: "Number of page views"
      - name: product_view_count
        description: "Number of product page views"
      - name: add_to_cart_count
        description: "Number of add-to-cart events"
      - name: search_count
        description: "Number of search events"
      - name: preferred_device
        description: "Most frequently used device"
      - name: preferred_browser
        description: "Most frequently used browser"
      - name: preferred_os
        description: "Most frequently used operating system"
      - name: total_app_events
        description: "Total number of app events"
      - name: total_app_sessions
        description: "Total number of app sessions"
      - name: app_active_days
        description: "Number of days with app activity"
      - name: total_app_time_seconds
        description: "Total time spent in the app (seconds)"
      - name: cart_to_order_conversion_rate
        description: "Ratio of orders to add-to-cart events"
      - name: view_to_cart_conversion_rate
        description: "Ratio of add-to-cart events to product views"
      - name: total_tickets
        description: "Total number of support tickets"
      - name: high_priority_tickets
        description: "Number of high or urgent priority tickets"
      - name: avg_satisfaction_rating
        description: "Average satisfaction rating for support tickets"
      - name: total_reviews
        description: "Total number of reviews submitted"
      - name: avg_review_score
        description: "Average review score (1-5)"
      - name: positive_reviews
        description: "Number of positive reviews (4-5)"
      - name: negative_reviews
        description: "Number of negative reviews (1-2)"

  - name: int_customer_support_performance
    description: "Support ticket performance metrics"
    columns:
      - name: ticket_id
        description: "Unique identifier for the support ticket"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Customer identifier"
        tests:
          - not_null
      - name: category
        description: "Support ticket category"
      - name: resolution_time_hours
        description: "Resolution time in hours"
      - name: resolution_time_category
        description: "Categorized resolution time"
        tests:
          - accepted_values:
              values: ['Unresolved', 'Under 1 hour', '1-4 hours', '4-24 hours', '1-3 days', 'Over 3 days']
      - name: satisfaction_rating
        description: "Customer satisfaction rating (1-5)"
        tests:
          - assert_valid_satisfaction_rating
      - name: satisfaction_score
        description: "Categorized satisfaction score"
        tests:
          - accepted_values:
              values: ['High', 'Medium', 'Low', null]

  - name: int_support_ticket_summary
    description: "Summary of support tickets by category and status"
    columns:
      - name: category
        description: "Support ticket category"
        tests:
          - not_null
          - unique
      - name: total_tickets
        description: "Total number of tickets in this category"
        tests:
          - not_null
      - name: open_tickets
        description: "Number of open tickets in this category"
      - name: in_progress_tickets
        description: "Number of in-progress tickets in this category"
      - name: resolved_tickets
        description: "Number of resolved tickets in this category"
      - name: closed_tickets
        description: "Number of closed tickets in this category"
      - name: cancelled_tickets
        description: "Number of cancelled tickets in this category"
      - name: avg_resolution_time_hours
        description: "Average resolution time in hours"
