version: 2

models:
  - name: customer_overview
    description: "Business-focused customer overview for analytics and reporting"
    columns:
      - name: customer_id
        description: "Unique identifier for a customer"
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: "Unique identifier that represents a customer across the platform"
      - name: customer_city
        description: "Customer city name"
      - name: customer_state
        description: "Customer state"
      - name: customer_segment
        description: "Customer segment based on RFM analysis"
      - name: customer_value_tier
        description: "Customer value tier (high, medium, low)"
      - name: first_order_date
        description: "Date of the customer's first order"
      - name: last_order_date
        description: "Date of the customer's most recent order"
      - name: days_since_last_order
        description: "Number of days since the customer's last order"
      - name: lifetime_orders
        description: "Total number of orders placed by the customer"
      - name: lifetime_value
        description: "Total value of all orders placed by the customer"
      - name: avg_order_value
        description: "Average order value for the customer"
      - name: preferred_category
        description: "Most frequently purchased product category"
      - name: preferred_payment_method
        description: "Most frequently used payment method"
      - name: satisfaction_score
        description: "Overall customer satisfaction score"
      - name: is_active
        description: "Flag indicating if the customer is active (ordered in last 90 days)"
      - name: churn_risk
        description: "Estimated risk of customer churn (high, medium, low)"
      - name: engagement_score
        description: "Overall engagement score based on web and app activity"

  - name: product_overview
    description: "Business-focused product overview for analytics and reporting"
    columns:
      - name: product_id
        description: "Unique identifier for a product"
        tests:
          - unique
          - not_null
      - name: product_category_name
        description: "Category name in original language"
      - name: product_category_name_english
        description: "Category name in English"
      - name: total_orders
        description: "Total number of orders containing this product"
      - name: total_units_sold
        description: "Total number of units sold"
      - name: total_revenue
        description: "Total revenue generated by this product"
      - name: avg_price
        description: "Average price of the product"
      - name: first_order_date
        description: "Date of the first order containing this product"
      - name: last_order_date
        description: "Date of the most recent order containing this product"
      - name: days_since_last_order
        description: "Number of days since the last order containing this product"
      - name: unique_customers
        description: "Number of unique customers who purchased this product"
      - name: repeat_purchase_rate
        description: "Rate at which customers purchase this product again"
      - name: avg_review_score
        description: "Average review score for this product"
      - name: return_rate
        description: "Rate at which this product is returned"
      - name: is_active
        description: "Flag indicating if the product is active (ordered in last 90 days)"
      - name: product_performance_score
        description: "Overall performance score for the product"

  - name: sales_overview
    description: "Business-focused sales overview for analytics and reporting"
    columns:
      - name: date_day
        description: "Date at day level"
        tests:
          - unique
          - not_null
      - name: year
        description: "Year"
      - name: month
        description: "Month"
      - name: day
        description: "Day"
      - name: day_of_week
        description: "Day of week (1-7)"
      - name: is_weekend
        description: "Flag indicating if the day is a weekend"
      - name: total_orders
        description: "Total number of orders placed on this day"
      - name: total_items_sold
        description: "Total number of items sold on this day"
      - name: total_revenue
        description: "Total revenue generated on this day"
      - name: total_freight_value
        description: "Total freight value on this day"
      - name: avg_order_value
        description: "Average order value on this day"
      - name: unique_customers
        description: "Number of unique customers who placed orders on this day"
      - name: new_customers
        description: "Number of new customers who placed their first order on this day"
      - name: canceled_orders
        description: "Number of orders canceled on this day"
      - name: top_selling_category
        description: "Top selling product category on this day"
      - name: top_selling_product
        description: "Top selling product on this day"

  - name: marketing_performance
    description: "Business-focused marketing performance overview for analytics and reporting"
    columns:
      - name: campaign_id
        description: "Unique identifier for the campaign"
        tests:
          - unique
          - not_null
      - name: campaign_name
        description: "Campaign name"
      - name: channel
        description: "Marketing channel"
      - name: campaign_type
        description: "Type of campaign"
      - name: start_date
        description: "Campaign start date"
      - name: end_date
        description: "Campaign end date"
      - name: duration_days
        description: "Campaign duration in days"
      - name: budget
        description: "Campaign budget"
      - name: impressions
        description: "Number of impressions"
      - name: clicks
        description: "Number of clicks"
      - name: conversions
        description: "Number of conversions"
      - name: revenue
        description: "Revenue generated"
      - name: ctr
        description: "Click-through rate (clicks / impressions)"
      - name: cvr
        description: "Conversion rate (conversions / clicks)"
      - name: cpa
        description: "Cost per acquisition (budget / conversions)"
      - name: roas
        description: "Return on ad spend (revenue / budget)"
      - name: target_audience
        description: "Target audience"
      - name: discount_percentage
        description: "Discount percentage if applicable"
      - name: campaign_performance_score
        description: "Overall performance score for the campaign"

  - name: customer_support_mart
    description: "Business-focused customer support overview for analytics and reporting"
    columns:
      - name: customer_id
        description: "Unique identifier for a customer"
        tests:
          - unique
          - not_null
      - name: customer_unique_id
        description: "Unique identifier that represents a customer across the platform"
      - name: customer_city
        description: "Customer city name"
      - name: customer_state
        description: "Customer state"
      - name: order_count
        description: "Total number of orders placed by the customer"
        tests:
          - not_null
      - name: total_spend
        description: "Total amount spent by the customer"
        tests:
          - not_null
      - name: ticket_count
        description: "Total number of support tickets created by the customer"
        tests:
          - not_null
      - name: avg_resolution_time
        description: "Average resolution time for customer's support tickets in hours"
      - name: avg_satisfaction
        description: "Average satisfaction rating for customer's support tickets"
      - name: satisfaction_segment
        description: "Customer segment based on support satisfaction"
        tests:
          - accepted_values:
              values: ['No Support Interaction', 'Highly Satisfied', 'Satisfied', 'Dissatisfied', 'Unknown']
